// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJXJXbE-Nod-tbcl3dBnXw8oI1E0eQ7cQ',
    appId: '1:422709480984:web:4b7d482cc6db83d8d0bd6d',
    messagingSenderId: '422709480984',
    projectId: 'telopago-dev',
    authDomain: 'telopago-dev.firebaseapp.com',
    storageBucket: 'telopago-dev.firebasestorage.app',
    measurementId: 'G-L6KEZYZ37V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9-gqCYHW356i3NWglX5tYfmFuOGNS9sk',
    appId: '1:422709480984:ios:e3b9325c38ff2d8ad0bd6d',
    messagingSenderId: '422709480984',
    projectId: 'telopago-dev',
    storageBucket: 'telopago-dev.firebasestorage.app',
    iosBundleId: 'com.example.telopago',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJXJXbE-Nod-tbcl3dBnXw8oI1E0eQ7cQ',
    appId: '1:422709480984:web:eceea7eb44dc9ddad0bd6d',
    messagingSenderId: '422709480984',
    projectId: 'telopago-dev',
    authDomain: 'telopago-dev.firebaseapp.com',
    storageBucket: 'telopago-dev.firebasestorage.app',
    measurementId: 'G-M56XQ5Z24D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9-gqCYHW356i3NWglX5tYfmFuOGNS9sk',
    appId: '1:422709480984:ios:e3b9325c38ff2d8ad0bd6d',
    messagingSenderId: '422709480984',
    projectId: 'telopago-dev',
    storageBucket: 'telopago-dev.firebasestorage.app',
    iosBundleId: 'com.example.telopago',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKzV1CcmSJUzhNdhPtVSTMtgCMGmTOBpY',
    appId: '1:422709480984:android:c6e48787e6b65fd7d0bd6d',
    messagingSenderId: '422709480984',
    projectId: 'telopago-dev',
    storageBucket: 'telopago-dev.firebasestorage.app',
  );

}